---
driver:
  name: docker
  use_sudo: false
  privileged: true
  provision_command:
    - /usr/bin/systemctl enable sshd
  run_command: /usr/sbin/init

provisioner:
  name: puppet_apply
#  puppet_version: latest
  manifests_path: test/integration
  modules_path: modules
#  hiera_data_path: hieradata

platforms:
#  - name: ubuntu-14.04
  - name: centos-7.2

suites:
  - name: multiple-instances
    manifest: multiple-instances/init.pp