---
driver:
  name: docker
  use_sudo: false
  privileged: true
  provision_command:
    - /usr/bin/systemctl enable sshd
  run_command: /usr/sbin/init

provisioner:
  name: puppet_apply
#  puppet_version: latest
  manifests_path: test/integration
  modules_path: modules
#  hiera_data_path: hieradata

platforms:
  - name: centos-7.2
    driver_config:
      provision_command:
        - yum update -y
        - yum install -y net-tools tar initscripts #initscipts - needed to manage services

suites:
  - name: multiple-instances
    manifest: multiple-instances/init.pp
  - name: remove-instance
    manifest: remove-instance/init.pp